# Generated by Django 4.2.29 on 2026-03-24 00:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodeLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_query', models.CharField(db_index=True, help_text='Lowercased, whitespace-normalized input query', max_length=512)),
                ('formatted_address', models.CharField(help_text='Google-formatted canonical address', max_length=1024)),
                ('latitude', models.DecimalField(db_index=True, decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(db_index=True, decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('place_id', models.CharField(help_text='Google Place ID — globally unique identifier', max_length=255, unique=True)),
                ('address_components', models.JSONField(default=dict, help_text='Raw address components from Google API response')),
                ('lookup_type', models.CharField(choices=[('forward', 'Forward'), ('reverse', 'Reverse')], db_index=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'geocode_lookups',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['normalized_query', 'lookup_type'], name='idx_query_type'), models.Index(fields=['latitude', 'longitude'], name='idx_lat_lng')],
            },
        ),
        migrations.CreateModel(
            name='DistanceCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('origin_lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('destination_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('destination_lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('distance_km', models.FloatField()),
                ('distance_miles', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'distance_calculations',
                'indexes': [models.Index(fields=['origin_lat', 'origin_lng'], name='idx_origin_coords'), models.Index(fields=['destination_lat', 'destination_lng'], name='idx_dest_coords')],
            },
        ),
    ]
